### ISSUE TITLE
tcpypi won't install

### ISSUE THREAD

**Issue by laurrrel** [dgilford/tcpyPI#53]
I'm trying to install tcpypi, but when I type "pip install tcpypi", I get the following error:

```
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/groups/oneillm/Laurel/miniconda3/envs/workenv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fwoeenty
       cwd: /tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/
  Complete output (26 lines):
  running bdist_wheel
  /home/groups/oneillm/Laurel/miniconda3/envs/workenv/bin/python /tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/subprocess.py", line 424, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/subprocess.py", line 505, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/subprocess.py", line 951, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/subprocess.py", line 1821, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/home/groups/oneillm/Laurel/miniconda3/envs/workenv/bin/python' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, xarray, numba, tcpypi
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.38.0
    Uninstalling llvmlite-0.38.0:
      Successfully uninstalled llvmlite-0.38.0
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/groups/oneillm/Laurel/miniconda3/envs/workenv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fkaw76ne/install-record.txt --single-version-externally-managed --compile --install-headers /home/groups/oneillm/Laurel/miniconda3/envs/workenv/include/python3.9/llvmlite
         cwd: /tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /home/groups/oneillm/Laurel/miniconda3/envs/workenv/bin/python /tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/subprocess.py", line 505, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/home/groups/oneillm/Laurel/miniconda3/envs/workenv/bin/python' failed with exit code 1
    ----------------------------------------
  Rolling back uninstall of llvmlite
  Moving to /home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/site-packages/llvmlite
   from /home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/site-packages/~lvmlite
  Moving to /home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/site-packages/llvmlite-0.38.0-py3.9.egg-info
   from /home/groups/oneillm/Laurel/miniconda3/envs/workenv/lib/python3.9/site-packages/~lvmlite-0.38.0-py3.9.egg-info
ERROR: Command errored out with exit status 1: /home/groups/oneillm/Laurel/miniconda3/envs/workenv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1hum5keb/llvmlite_30d4375db3ee4b6d950f7cbfd970364a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fkaw76ne/install-record.txt --single-version-externally-managed --compile --install-headers /home/groups/oneillm/Laurel/miniconda3/envs/workenv/include/python3.9/llvmlite Check the logs for full command output.
```

What might I do to fix this? Is there some other thing that I need to install? Or a module that I need?

Thanks!

**Comment by dgilford** [comment]
Linking to #47 , where I am addressing this now.
