### ISSUE TITLE
 python run_sample.py ERROR 

### ISSUE THREAD

**Issue by Wamashudu** [dgilford/tcpyPI#68]
Performing PI analyses...
Traceback (most recent call last):

  File "/home/wamashudu/Videos/Potnetail intensity/tcpyPI-master/run_sample.py", line 148, in <module>
    ds2 = run_sample_analyses(ds,_mdrF,CKCD=0.9)
  File "/home/wamashudu/Videos/Potnetail intensity/tcpyPI-master/run_sample.py", line 73, in run_sample_analyses
    basins = pickle.load( open( _mdrF, "rb" ) )

AttributeError: Can't get attribute 'PandasIndexAdapter' on <module 'xarray.core.indexing' from '/home/wamashudu/anaconda3/lib/python3.9/site-packages/xarray/core/indexing.py'>

**Comment by dgilford** [comment]
Hello,

I looked more closely and see where the error is occurring now, in the run_sample_analyses() function. This function is meant as general set of interesting post-calculation analyses to show pyPI example applications. As such, it is not critical to the calculation of potential intensity. In that sense, it’s worth noting that you should still be getting valid outputs in your ds dataset, and raw_sample_output.nc will still have all of the output from the pi.py module. If you plan to use tcpyPI to calculate potential intensity with your own input data, then this error will not be directly relevant for your application.

That said, it's useful to get this up and running for general education and understanding of how the package works, so I'll get to work fixing it!

The “AttributeError” we are running into is related to a mismatch in the version of [pickle](https://docs.python.org/3/library/pickle.html) used to save out the original [mdr.pk1](data/mdr.pk1) pickle file, and the version of xarray we are using to load in the file. [See a related problem here](https://stackoverflow.com/questions/69837913/attributeerror-cant-get-attribute-pandasindexadapter-on-module-xarray-core).

I will plan to change the source of the mdr data to a more stable file type and push the change to the package soon.


In the meantime, please let me know if you encounter other errors that are outside code problematic calls for the [mdr.pk1](data/mdr.pk1) (e.g. in this sample analysis)

**Comment by dgilford** [comment]
Duplicate of #48

**Comment by Wamashudu** [comment]
Thank you so much !

**Comment by dgilford** [comment]
This has been changed to a *json file as part of modernization (#71  )
